id: I8828F22F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T13:24:49+00:00'
last_modified: '2022-06-07T10:38:12.373861+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W17836
  title: གསུང་སྒྲོས་ཕན་བྱེད་རིག་པའི་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B358:
      image_group_id: I1GS57578
      title: Volume 1 of gsung sgros phan byed rig pa'i mdzod
      total_pages: 135
      order: 1
      base_file: B358.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
